showing_helpbox = false;
current_page = 0;

help_pages = [
    "Community Cooking Manual\n\nWelcome to Community Cooking, a post-apocalyptic survival cooking simulator. Your goal is to prepare nutritious meals for your community by talking to NPCs, gathering ingredients, preparing and cooking dishes, and serving them.",

    "Phase One: Prep and Planning\n\nTalk to NPCs\nAt the start of the day, go outside from the kitchen area to the serving area.\n\nTalk to NPCs to see their nutrient needs:\n- Fullness\n- Vitamins\n- Protein\n- Salt\n\nYou’ll see these displayed above their heads. (To be changed into a conversation)\n\nPlan the Recipes\nEach dish consists of 2 main ingredients\nThe nutrients of a dish = sum of nutrients of its 2 ingredients.\n\nFor example:\nPotato (F:4, P:2) + Carrot (F:3, V:2) = Dish (F:7, P:2, V:2)\n\n⚠️ You need to prepare as many dishes as there are NPCs.\n\nPick Ingredients in Order\nHead back inside to the pantry.\nChoose your ingredients in the order you’ll prep and cook them.\n\nThe order matters because:\n- Ingredients must be prepped in the chosen order.\n- Dishes are cooked using 2 ingredients at a time.\n\nPrep Ingredients\nUse the cutting board, mashing station, etc.\nInteract with them to play their corresponding minigames.\n\nOnce an ingredient is prepped, it moves to your prepared list.\nYour TO DO list shows the tasks remaining for this phase.",

    "Phase Two: Cooking Phase\n\nAdd Ingredients to Pot\nYou can only add 2 ingredients (non-spice) at a time.\nWalk up to the stove pot and press Enter to add the first 2 from your prepared list.\nSpices can be added at any time.\n\nCooking Mechanics\nOnce 2 ingredients are in, cooking automatically starts.\nThe cooking progress bar increases over time.\nBut heat also rises.\nIf heat > 100, the dish burns and nutrient values are halved.\nInteract with the pot again to play the cooling minigame.\n\nFinishing a Dish\nOnce the dish is done:\n- It’s named based on matching recipes.\n- The quantity is determined by the minimum quantity of the two ingredients used.\n- The dish is added to your inventory and available for serving.\n\nOnce all dishes are cooked and the pot is idle, you’ll be prompted to move to the serving phase.",

    "Phase Three: Serving the Community\n\nApproach NPCs\nGo back to the serving area.\nWalk up to an NPC and press Enter.\nA UI will appear showing all your available dishes.\n\nChoose a Dish\nPress keys 1–9 to select a dish.\nEach NPC accepts 1 dish.\nTheir reaction is based on how well the dish nutrients match their needs:\n- > 80% Match = Good\n- 50–80% Match = Neutral\n- < 50% Match = Bad\n\nFinal Result\nOnce all NPCs have been served, a Result Screen will pop up:\n- Tally of Good, Neutral, and Bad reactions.\n- Overall feedback and time of day.\n\nTips\n- Always check NPC needs before entering the pantry.\n- Choose ingredient pairs wisely.\n- Avoid burning by watching the heat meter.\n\nRemember: Nutrition = Strategy.\nGood luck, Chef. The community is counting on you."
];

